#pragma once
enum Header { CONNECT, START, UPDATE_POSITIONS, YOUR_TURN, MOVE, GUESS, SUPOSE, ACUSE, ACUSE_SUCCESS, ACUSE_FAIL, SHOW_CARDS, SHOWING_CARDS };
enum HeaderUDP { STARTUDP, UPDATE_POSITIONSUDP, MOVE};