#pragma once
enum Header { CONNECT, START, UPDATE_POSITIONS, YOUR_TURN, MOVE, GUESS, SUPOSE, ACUSE, ACUSE_SUCCESS, ACUSE_FAIL, SHOW_CARDS, SHOWING_CARDS };
enum HeaderUDP { STARTUDP, UPDATE_POSITIONSUDP, MOVEUDP};
enum UDPGameProtocol {};
enum UDPGameCommands { MOVE_COMMAND = 3949435, SHOOT = 1856186586 };

