#pragma once
typedef enum Actions {
	START,		//<START>_<SELECT_COLOR>_<POSITION>_<GIVEN_CARDS_NUMBER>_<CARD_IDs0... ...CARD_IDsN>
	SET_ID,		//<SET_ID>_<N>
	YOUR_TURN,	//<YOUR_TURN>_<N>_<POSITION>_<DICE_1>_<DICE_2>_<BOOL_CLUE_CARD>_
	END_TURN,	//<END_TURN>_<REQUESTED_NEW_LOCATION>
};